---

- name: add nodejs apt key
  apt_key:
    url: "{{ node_apt_key }}"
    state: present

- name: add nodejs repository
  apt_repository:
    repo: "{{ node_repository }}"
    state: present

- name: update apt and install nodejs
  apt:
    name: nodejs
    state: latest
    update_cache: true
